### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by MichielDx** [wayofthefuture/react-input-moment#1]
Hello

I get this error in your src/index.js file. It's on this line: `import _InputMoment from './InputMoment';`

**Comment by wayofthefuture** [comment]
How are you using it? Are you using npm start?

**Comment by MichielDx** [comment]
I tried npm start, aswel as installing it in my project. Both give the same error, could it be that I'm missing a loader?

**Comment by MichielDx** [comment]
even npmrunkit gives errors [https://npm.runkit.com/react-input-moment](url)

**Comment by wayofthefuture** [comment]
Thank you for letting me know. The lib was being ignored in .gitignore so it wasn't being published. Please update and try again.

**Comment by MichielDx** [comment]
This works! 👍
