### ISSUE TITLE
Add steps to the time slider

### ISSUE THREAD

**Issue by smeijer** [wayofthefuture/react-input-moment#2]
I think the version where we only have the single time slider, would benefit greatly from this feature. 

A `steps` property with a value of `5` would mean that only the 5 minute intervals can be selected (5, 10, 15,...)

As also described in https://github.com/wangzuo/input-moment/issues/64

**Comment by wayofthefuture** [comment]
Which time sliders? All of them? It shouldn't be that hard to implement. It would depend on the underlying slider framework if it has that option. Open to pull requests.

**Comment by kenneho** [comment]
Is it [react-input-slider](https://www.npmjs.com/package/react-input-slider) you're using? If so, it's looks like it got support for this, using the xstep parameter.

**Comment by smeijer** [comment]
It looks like it is indeed `react-input-slider`. This would be awesome.

**Comment by wayofthefuture** [comment]
+1

**Comment by wayofthefuture** [comment]
Yeah it wasn't good on mobile defaults defaulted to 5 steps.
