### ISSUE TITLE
MIN prop bad behaviour

### ISSUE THREAD

**Issue by Geekstips** [wayofthefuture/react-input-moment#5]
I set min props = { moment () } which should be today ( 08.03.2018 ). When I open the plugin first day available to select is yesterday ( 07.03.2018 ). After I chose any date, the yesterday date becomes unavailable and first day available becomes today. Seems that the min effect is fired after onChange event somehow. Also in console I get a warning message which says that min prop value Moment is not what expected ( instance of `hooks` ). Please help!

**Comment by wayofthefuture** [comment]
Date ranges ? I don't know if we have ever tested that. Please create a pull request and I'll merge.
