### ISSUE TITLE
Upgrade React version 16

### ISSUE THREAD

**Issue by truongthanh1303** [wayofthefuture/react-input-moment#8]
Hi @wayofthefuture,
Thanks for your works, I have a problem with this lib in a source code with React version 16.
Could you please help me to upgrade the React version to 16?
And on the other hand, what do you think about moving the react and react-dom to the devDependencies instead of the dependencies?

Regards,

**Comment by wayofthefuture** [comment]
All you have to do is change the version numbers, test and do a pull request.

They should not be in the dev dependencies section.

**Comment by truongthanh1303** [comment]
Hi,
Follow [the requirement](https://github.com/wayofthefuture/react-input-moment#requirements), the react and react-dom will not include in the build. But when I install react-input-moment into an empty source, I saw the react and react-dom in the node_modules folder.

![image](https://user-images.githubusercontent.com/7240446/43561817-0b9c317c-9643-11e8-9935-bdedbe3163e6.png)
![image](https://user-images.githubusercontent.com/7240446/43561840-25d00dd4-9643-11e8-809c-4a98f083983d.png)

Could you please explain this for me to understand?

Regards,

**Comment by wayofthefuture** [comment]
Sorry I understand now. That is a bug and was done in error... the react dependencies need to be removed from this repo package.json.

**Comment by wayofthefuture** [comment]
Thanks for this! All done!
